export enum UserRole {
  CompanyAdmin = 'CompanyAdmin',
  BrandAdmin = 'BrandAdmin',
  SalesHOD = 'SalesHOD',
  RetentionHOD = 'RetentionHOD',
  SupportHOD = 'SupportHOD',
  PspHOD = 'PspHOD',
  SalesManager = 'SalesManager',
  RetentionManager = 'RetentionManager',
  SupportManager = 'SupportManager',
  PSPManager = 'PSPManager',
  BOManager = 'BOManager',
  ComplianceManager = 'ComplianceManager',
  OperationsManager = 'OperationsManager',
  DealingManager = 'DealingManager',
  SalesLead = 'SalesLead',
  RetentionLead = 'RetentionLead',
  SupportLead = 'SupportLead',
  SalesAgent = 'SalesAgent',
  RetentionAgent = 'RetentionAgent',
  SupportAgent = 'SupportAgent',
  AffiliateManager = 'AffiliateManager',
  Client = 'Client',
  Affiliate = 'Affiliate',
  Lead = 'Lead',
  Worker = 'Worker',
  Operator = 'Operator',
  SuperAdmin = 'SuperAdmin',
  MrRobot = 'MrRobot',
}

export enum UserPermission {
  AffiliateManager_Executive = 'Affiliate manager.Executive',
  AffiliateManager_TeamLead = 'Affiliate manager.Team leader',
  AffiliateManager_HOD = 'Affiliate manager.Head of department',
  AffiliateManager_Manager = 'Affiliate manager.Manager',
  Compliance = 'Compliance.Compliance',
  Compliance_Manager = 'Compliance.Compliance manager',
  Finance_Executive = 'Finance.Executive',
  Finance_TeamLead = 'Finance.Team leader',
  Finance_HOD = 'Finance.Head of department',
  Finance_Manager = 'Finance.Manager',

  MrRobot = 'MrRobot',
}
